# GOOD ENDPOINTS
#    GET    /
#    POST   /
#    GET    /:rentalId
#    PUT    /:rentalId
#    DELETE /:rentalId
# BAD ENDPOINTS
#    PUT    /
#    DELETE /
#    POST   /:rentalId

openapi: 3.0.0

info:
  version: 1.0.0
  title: rentals API
  description: An API to interact with the rentals database

servers:
  - url: http://127.0.0.1:3001/api

paths:
  /rentals:
    get:
      description: Returns a list of rentals
      responses:
        "200":
          description: Successfully returned a list of genres
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Rental"
    post:
      description: Lets a user create a new rental
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Rental"
      responses:
        "400":
          description: Bad request due to body or movie not in stock
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "200":
          description: Successfully posted a new rental
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rental"
        "404":
          description: Customer or movie not found
          content:
            appication/json:
              schema:
                $ref: "#/components/schemas/Error"

  /rentals/{rentalId}:
    get:
      description: Get a single rental
      parameters:
        - name: rentalId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully returned a single rental
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rental"
        "404":
          description: rental was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Rental:
      type: object
      properties:
        _id:
          type: string
        dateOut:
          type: string
        dateReturned:
          type: integer
        rentalFee:
          type: integer
        customer:
          type: object
          properties:
            customerId:
              type: string
            name:
              type: string
            dateJoined:
              type: string
            phone:
              type: string
            email:
              type: string
            isGold:
              type: boolean
            imageSrc:
              type: string
        movie:
          type: object
          properties:
            movieId:
              type: string
            title:
              type: string
            genre:
              type: object
              properties:
                genreId:
                  type: string
                name:
                  type: string
            numberInStock:
              type: integer
            publishDate:
              type: string
            liked:
              type: boolean
    Error:
      type: object
      properties:
        message:
          type: string

  # define a security scheme for JWT required endpoints
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    # define a security scheme for basic auth required endpoints
    BasicAuth:
      type: http
      scheme: basic
# define all endpoints to use basic auth
# [] is used to specified required scopes (permissions)
# security:
#   - BasicAuth[]
